# [START app_yaml]
runtime: nodejs
env: flex
manual_scaling:
  instances: 1

# [START env]
# The following env variables may contain sensitive information that grants
# anyone access to your database. Do not add this file to your source control.
env_variables:
  SQL_USER: SQL아이디
  SQL_PASSWORD: SQL비밀번호
  SQL_DATABASE: DB이름
  # e.g. my-awesome-project:us-central1:my-cloud-sql-instance
  INSTANCE_CONNECTION_NAME: SQL 인스턴스 커넥션 이름

# [END env]

# [START cloudsql_settings]
beta_settings:
  # The connection name of your instance, available by using
  # 'gcloud beta sql instances describe [INSTANCE_NAME]' or from
  # the Instance details page in the Google Cloud Platform Console.
  cloud_sql_instances: SQL 인스턴스 커넥션 이름
# [END cloudsql_settings]
# [END app_yaml]
